/**
 * Environment Variables
 */

const ENV = process.env;
const ENVIRONMENT_VARIABLES = {
  NODE_ENV: ENV.NODE_ENV,
  APPLICATION_NAME: ENV.APPLICATION_NAME,
  AWS_ASSUME_ROLE_ARN: ENV.AWS_ASSUME_ROLE_ARN || 'arn:aws:iam::123456789101:role/spectrum-role',
  AWS_SESSION_TOKEN: ENV.AWS_SESSION_TOKEN,
  AWS_ACCESS_KEY: ENV.AWS_ACCESS_KEY,
  AWS_SECRET_ACCESS_KEY: ENV.AWS_SECRET_ACCESS_KEY,
  FARGATE_BUILD_TYPE: ENV.FARGATE_BUILD_TYPE,
  FARGATE_ACCOUNT_ID: ENV.FARGATE_ACCOUNT_ID,
  FARGATE_STACK_NAME: ENV.FARGATE_STACK_NAME,
  FARGATE_ENVIRONMENT: ENV.FARGATE_ENVIRONMENT,
  FARGATE_REGION: ENV.FARGATE_REGION || 'us-east-1',
  FARGATE_TAGS_FILE: ENV.FARGATE_TAGS_FILE,
  ...ENV, // Load the rest of the env variables
};

module.exports = ENVIRONMENT_VARIABLES;
